### ISSUE TITLE
failure to to partition device

### ISSUE THREAD

**Issue by imle** [siderolabs/go-blockdevice#37]
failed to partition device: requested partition size 104857600, available is 72879104 (31978496 too many bytes)

Talos: 0.10.1

Installer: ghcr.io/talos-systems/installer:v0.10.1

Server: `HP Proliant DL380 G7`

Disks:
```
DEV        MODEL            SERIAL   TYPE   UUID   WWID   MODALIAS      NAME   SIZE
/dev/sda   LOGICAL VOLUME   -        HDD    -      -      scsi:t-0x00   -      120 GB
/dev/sdb   Flash Reader     -        HDD    -      -      scsi:t-0x00   -      7.7 GB
```

Code seems to consistently ask for 100 GiB regardless of the size of the disk it is being installed on.

**Comment by smira** [comment]
This should be fixed hopefully.
