### ISSUE TITLE
ZFS

### ISSUE THREAD

**Issue by smira** [siderolabs/go-blockdevice#84]
See https://github.com/util-linux/util-linux/blob/c0207d354ee47fb56acfa64b03b5b559bb301280/libblkid/src/superblocks/zfs.c#L252-L258

Probe the absolute minimum - just identify the ZFS, whatever is easy to get. If getting UUID/Label is hard, we can skip it for now.

**Comment by dsseng** [comment]
ZFS-FUSE is not available in Alpine, and common ZFS programs cannot create a pool without kernel driver being present, which we cannot provide in a container. Maybe we could add a compressed test image as a fixture for testing ZFS probing support?

**Comment by frezbo** [comment]
adding  a compressed raw image is fine as long as the test data is easily reproducable

**Comment by dsseng** [comment]
Well, we could potentially build it with zfs-fuse in a separate container

**Comment by frezbo** [comment]
> Well, we could potentially build it with zfs-fuse in a separate container

I meant just that running same commands produce the same test data, you can generate locally and add it

**Comment by dsseng** [comment]
[These offsets](https://github.com/util-linux/util-linux/blob/c0207d354ee47fb56acfa64b03b5b559bb301280/libblkid/src/superblocks/zfs.c#L275-L280) appear hard to get in our case because these are magics offset from the end of partition. Maybe we could somehow implement ZFS as magicless probe going straight into the Probe function?

**Comment by smira** [comment]
We do support zero magic, but what is missing is that you're missing blockdevice size?

**Comment by dsseng** [comment]
Cannot I know it by using the same method GPT probing calls? Or that only works for devices not partitions?

**Comment by smira** [comment]
Yes, you can use same approach as GPT
