### ISSUE TITLE
Linux swap

### ISSUE THREAD

**Issue by smira** [siderolabs/go-blockdevice#85]
See https://github.com/util-linux/util-linux/blob/c0207d354ee47fb56acfa64b03b5b559bb301280/libblkid/src/superblocks/swap.c#L138-L159

Don't need to detect old formats (as we run recent Linux 6.6), no need to detect suspend (not our case).

Most important is detection - detect that it's there.

**Comment by dsseng** [comment]
Fixed by https://github.com/siderolabs/go-blockdevice/pull/89
